/**
 * SPIKE — real TAURUS vault on tachi-regtest-1: L1 fund → createVault →
 * depositToVault → registerVault → unilateral exit back to L1 (+ cooperative
 * refund on a second vault if time allows). Not wired into the product.
 * Every stage prints the daemon's real responses and appends to
 * docs/tachi-vault-spike.md; state in .tachi-spike-state.json (gitignored)
 * makes reruns resume. Stops at the first hard blocker and records it.
 *
 *   npm run spike:vault           SPIKE_CSV=1 (exit-leaf CSV blocks, default 1)
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import * as bitcoin from "bitcoinjs-lib";
import * as ecc from "@bitcoinerlab/secp256k1";
import { BIP32Factory } from "bip32";
import * as bip39 from "bip39";
import { TachiClient } from "@tachibtc/tachi-sdk-ts";
import { BitcoinCoreRpcClient, WalletAggregator } from "@tachibtc/taurus-wallet-aggregator";
import {
  applyRefundCosignPartials, buildRefundPsbt, buildToLocalP2trOutput, buildUnilateralExitPsbt, cosignRefund, createVault,
  depositToVault, fetchConsensusQuorum, finalizeRefundPsbt, finalizeUnilateralExitPsbt, getLockedVtxos, listVaults,
  normalizeTaprootSigner, registerVault, signRefundPsbtAsUser, signUnilateralExitPsbtAsUser, verifyRefundPsbt,
  verifyUnilateralExitPsbt, type Vault,
} from "@tachibtc/taurus-vault-core";

bitcoin.initEccLib(ecc);
const bip32 = BIP32Factory(ecc);
const RPC = process.env.TACHI_RPC_URL ?? "https://rpc-regtest.tachibtc.com";
const FAUCET = "https://faucet.tachibtc.com";
const STATE = process.env.SPIKE_STATE ?? ".tachi-spike-state.json";
const DOC = "docs/tachi-vault-spike.md";
const CSV = Number(process.env.SPIKE_CSV ?? "1");
const DEPOSIT = 300_000n;
const EXIT_FEE = 500n;
const net = bitcoin.networks.regtest;

// ---- state + doc --------------------------------------------------------
type State = Record<string, any>;
const state: State = existsSync(STATE) ? JSON.parse(readFileSync(STATE, "utf8")) : { sections: [] };
const save = () => { writeFileSync(STATE, JSON.stringify(state, (_k, v) => (typeof v === "bigint" ? v.toString() : v), 2), { mode: 0o600 }); writeFileSync(DOC, `# Tachi vault spike — real TAURUS vault, L1 in, unilateral exit out (tachi-regtest-1)\n\nGenerated by \`npm run spike:vault\` (scripts/tachi-vault-spike.ts). Every block is a real daemon/L1 response. Exit-leaf CSV for this run: **${CSV} block(s)** (default 1008 would be ~7 days at regtest's 10-min cadence).\n\n${(state.sections as string[]).join("\n\n")}\n`); };
const j = (x: unknown) => JSON.stringify(x, (_k, v) => typeof v === "bigint" ? `${v}n` : Buffer.isBuffer(v) ? v.toString("hex") : v instanceof Uint8Array ? Buffer.from(v).toString("hex") : v, 2);
const stamp = () => new Date().toISOString().slice(11, 19) + "Z";
function log(title: string, body: string) { const s = `## ${title}\n\n_${stamp()}_\n\n${body}`; console.log("\n" + s); state.sections.push(s); save(); }
const rec = (t: string, v: unknown, note?: string) => log(t, `${note ? note + "\n\n" : ""}\`\`\`json\n${j(v)}\n\`\`\``);
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

// ---- clients --------------------------------------------------------------
const client = new TachiClient({ baseUrl: RPC });
const rpc = new BitcoinCoreRpcClient({ url: RPC });
const btc = async (method: string, params: unknown[] = []) => { const r = await client.bitcoinRPC({ method, params }); if (r.error) throw new Error(`bitcoinRPC ${method}: ${JSON.stringify(r.error)}`); return r.result as any; };

async function waitConfirmations(txid: string, need: number, label: string, maxMin = 25): Promise<{ confirmations: number; blockhash: string; waitedSec: number }> {
  const t0 = Date.now();
  for (;;) {
    const r = await btc("getrawtransaction", [txid, true]);
    const c = r?.confirmations ?? 0;
    if (c >= need) return { confirmations: c, blockhash: r.blockhash, waitedSec: Math.round((Date.now() - t0) / 1000) };
    if (Date.now() - t0 > maxMin * 60_000) throw new Error(`timed out after ${maxMin} min waiting for ${need} confirmation(s) of ${label} ${txid} (have ${c})`);
    process.stdout.write(`  … ${label} ${c}/${need} conf, L1 height ${await btc("getblockcount")}, ${stamp()}\r`);
    await sleep(20_000);
  }
}

async function main() {
  const t0 = Date.now();
  log("Run", `- when: ${new Date().toISOString()}\n- rpc: \`${RPC}\`\n- csvBlocks: ${CSV}\n- L1 cadence observed before the run: one block every **10 minutes** at :x0:01 (heights 9566→9573, 1–2 tx each)`);

  // ---- 1. L1 wallet ---------------------------------------------------------
  if (!state.mnemonic) { state.mnemonic = bip39.generateMnemonic(128); save(); }
  const root = bip32.fromSeed(await bip39.mnemonicToSeed(state.mnemonic), net);
  const agg = WalletAggregator.fromMnemonic(state.mnemonic, { network: "regtest", rpc });
  const wallet = agg.addAccount({ addressType: "p2wpkh" });
  const signerAt = (i: number) => normalizeTaprootSigner(root.derivePath(`m/84'/1'/0'/0/${i}`));
  const xOnlyAt = (i: number) => Buffer.from(root.derivePath(`m/84'/1'/0'/0/${i}`).publicKey).subarray(1, 33);
  if (!state.faucetTxid) {
    const addr = wallet.receiveAddress; state.p2wpkh = addr;
    const res = await fetch(`${FAUCET}/api/faucet`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ address: addr, amountBtc: 0.01, proof: null }) });
    const body = await res.json(); state.faucetTxid = body.txid; state.faucetClaimedAt = new Date().toISOString(); save();
    rec("1. faucet POST /api/faucet (L1 coins to our P2WPKH)", body, `address \`${addr}\``);
  }
  const fc = await waitConfirmations(state.faucetTxid, 1, "faucet tx");
  await wallet.sync();
  rec("1. L1 wallet (aggregator, synced through the daemon's Bitcoin RPC proxy)", { p2wpkh: wallet.receiveAddress, balance: wallet.balance, utxos: wallet.utxos, faucet: { txid: state.faucetTxid, claimedAt: state.faucetClaimedAt, ...fc } },
    "Stage 1 complete: a confirmed L1 UTXO the aggregator can spend. (The faucet claim happened to land in the very next 10-minute block.)");

  // ---- 2. createVault -------------------------------------------------------
  const quorum = await fetchConsensusQuorum({ baseUrl: RPC });
  rec("2. fetchConsensusQuorum (/tachi_validatorsPower) — the quorum every vault script commits to", { source: quorum.source, threshold: quorum.threshold, totalValidators: quorum.totalValidators, secp256k1Count: quorum.secp256k1Count, nodePubkeys: quorum.nodePubkeys });
  const mkVault = (i: number) => createVault({ network: "regtest", userWallet: wallet, userKeyIndex: i, nodePubkeys: quorum.nodePubkeys, threshold: quorum.threshold, csvBlocks: CSV });
  const vaultA: Vault = await mkVault(0);
  const vaultB: Vault = await mkVault(1);
  const vaultView = (v: Vault) => ({ address: v.p2tr.address, output: v.p2tr.output, internalKey: v.p2tr.internalKey, taprootOutputKey: v.p2tr.taprootOutputKey, cooperativeLeaf: { threshold: v.p2tr.cooperativeLeaf.threshold, totalNodes: v.p2tr.cooperativeLeaf.totalNodes, userKey: v.p2tr.cooperativeLeaf.userKey, leafHash: v.p2tr.cooperativeLeafHash }, exitLeaf: { csvBlocks: v.p2tr.exitLeaf.csvBlocks, userKey: v.p2tr.exitLeaf.userKey, script: v.p2tr.exitLeaf.script, leafHash: v.p2tr.exitLeafHash }, userKey: v.userKey });
  rec("2. createVault — vault A (exit test, userKeyIndex 0)", vaultView(vaultA), "Local, no daemon call. No apiKey needed to CREATE; the apiKey only matters for `listVaults` returning reconstruction params.");
  rec("2. createVault — vault B (cooperative-refund test, userKeyIndex 1)", { address: vaultB.p2tr.address, userKey: vaultB.userKey.compressedHex, csvBlocks: vaultB.p2tr.exitLeaf.csvBlocks });

  // ---- 3. depositToVault (A) -------------------------------------------------
  if (!state.depositA) {
    const t = Date.now();
    const dep = await depositToVault({ vault: vaultA, userWallet: wallet, rpc, amountSats: DEPOSIT, feeRateSatVb: 2 });
    const tx = bitcoin.Transaction.fromHex(dep.rawTxHex);
    const vout = tx.outs.findIndex((o) => Buffer.from(o.script).equals(vaultA.p2tr.output));
    state.depositA = { txid: dep.txid, vout, amountSats: dep.amountSats.toString(), feeSats: dep.feeSats.toString(), changeSats: dep.changeSats.toString(), broadcastAt: new Date().toISOString(), buildMs: Date.now() - t }; save();
    rec("3. depositToVault A — L1 funding tx broadcast (via proxy sendrawtransaction)", { ...state.depositA, rawTxHex: dep.rawTxHex });
  }
  const cA = await waitConfirmations(state.depositA.txid, 1, "deposit A");
  state.depositA.confirmedAt = new Date().toISOString(); save();
  rec("3. deposit A confirmed", { ...cA, broadcastAt: state.depositA.broadcastAt, confirmedAt: state.depositA.confirmedAt }, `**Wall clock: ${cA.waitedSec}s from the first poll** (regtest mines every 10 minutes).`);

  // ---- 4. registerVault (A) --------------------------------------------------
  if (!state.registerA) {
    const fee = state.feeVtxos["0"];
    const reg = await registerVault({
      vault: vaultA,
      outpoint: { fundingTxid: Buffer.from(state.depositA.txid, "hex").reverse(), fundingVout: state.depositA.vout },
      userSigner: signerAt(0),
      inputs: [{ vtxoId: Buffer.from(fee.id, "hex"), valueSats: BigInt(fee.sats) }],
      outputs: [{ owner: xOnlyAt(0), amount: BigInt(fee.sats) - 1n }],
      feeSats: 1n,
      broadcast: { url: `${RPC}/tachi_txBroadcastSync` }, account: { baseUrl: RPC },
      confirm: { baseUrl: RPC },
    });
    state.registerA = { vaultId: reg.vaultIdHex, nonce: reg.nonce.toString(), broadcast: reg.broadcast, commit: reg.commit ? { hash: reg.commit.hash, committed: reg.commit.committed, code: reg.commit.code, log: reg.commit.log, state: reg.commit.state } : null }; save();
    rec("4. registerVault A — TxVaultOpen (fee paid from a 2 000-sat ledger VTXO on the user key)", state.registerA);
  }
  const lv = await listVaults(vaultA.userKey.compressedHex!, { baseUrl: RPC });
  rec("4. listVaults(userKey) — daemon's view (no apiKey → reconstruction params redacted)", lv);
  const locked = await getLockedVtxos(vaultA.p2tr.address, { baseUrl: RPC });
  rec("4. getLockedVtxos(vault A address)", locked);

  // ---- 5. value on the ledger side -------------------------------------------
  const vaultVtxos = await client.getAddressVtxos(vaultA.p2tr.address, true);
  const vaultBal = await client.getBalance(vaultA.p2tr.address);
  const l1 = await btc("gettxout", [state.depositA.txid, state.depositA.vout]);
  rec("5. does the vault hold usable value?", { ledger: { getAddressVtxos: vaultVtxos, getBalance: vaultBal }, l1FundingUtxo: l1 },
    "Ledger = what the daemon credits the vault address / its locked VTXOs; L1 = the funding UTXO the exit will spend.");

  // ---- 6. unilateral exit PSBT ------------------------------------------------
  const exitOut = { address: state.p2wpkh ?? wallet.receiveAddress, valueSats: DEPOSIT - EXIT_FEE };
  const built = buildUnilateralExitPsbt({ vault: vaultA, funding: { txid: state.depositA.txid, vout: state.depositA.vout, valueSats: DEPOSIT, scriptPubKey: vaultA.p2tr.output.toString("hex") }, outputs: [exitOut], feeSats: EXIT_FEE });
  const opts = { maxFeeSats: 1_000n, minCsvBlocks: CSV };
  verifyUnilateralExitPsbt(built.psbt, vaultA, { ...opts, expectedUserKey: vaultA.p2tr.exitLeaf.userKey });
  await signUnilateralExitPsbtAsUser(built.psbt, signerAt(0), vaultA, opts);
  const exitHex = finalizeUnilateralExitPsbt(built.psbt, vaultA, { ...opts, expectedUserKey: vaultA.p2tr.exitLeaf.userKey });
  const exitTx = bitcoin.Transaction.fromHex(exitHex);
  state.exit = { hex: exitHex, txid: exitTx.getId(), sequence: built.sequence, csvBlocks: vaultA.p2tr.exitLeaf.csvBlocks, vsize: exitTx.virtualSize(), feeSats: EXIT_FEE.toString(), to: exitOut }; save();
  rec("6. buildUnilateralExitPsbt → verify → signUnilateralExitPsbtAsUser → finalize (user signature ONLY, no quorum)", { ...state.exit, psbtBase64: built.psbt.toBase64().slice(0, 120) + "…", controlBlock: built.controlBlock, witnessItems: exitTx.ins[0]!.witness.length },
    `nSequence = ${built.sequence} (BIP-68 relative lock = CSV ${vaultA.p2tr.exitLeaf.csvBlocks} block(s)); valid once the funding output has ≥${CSV} confirmation(s).`);

  // ---- 7. broadcast the exit --------------------------------------------------
  if (!state.exitBroadcast) {
    try {
      const txid = await btc("sendrawtransaction", [exitHex]);
      state.exitBroadcast = { ok: true, txid, at: new Date().toISOString() }; save();
      rec("7. sendrawtransaction(exit) — L1 accepted the unilateral exit into the mempool", state.exitBroadcast);
    } catch (e) {
      state.exitBroadcast = { ok: false, error: e instanceof Error ? e.message : String(e), at: new Date().toISOString() }; save();
      rec("7. sendrawtransaction(exit) — REJECTED", state.exitBroadcast, "Verbatim L1 error. If this is BIP-68 non-final, the funding output needs more confirmations than it has.");
      throw new Error("exit broadcast rejected — see doc");
    }
  }
  const cE = await waitConfirmations(state.exit.txid, 1, "exit tx");
  await wallet.sync();
  const daemonAfter = { listVaults: await listVaults(vaultA.userKey.compressedHex!, { baseUrl: RPC }), locked: await getLockedVtxos(vaultA.p2tr.address, { baseUrl: RPC }), watchtower: await client.getWatchtowerReceipts().catch((e: Error) => ({ error: e.message })) };
  rec("7. EXIT CONFIRMED ON L1 — the win", { exitTxid: state.exit.txid, ...cE, l1WalletAfter: { balance: wallet.balance, utxos: wallet.utxos }, daemonAfter },
    `**A real unilateral exit: ${DEPOSIT - EXIT_FEE} sats swept from the vault's exit leaf back to our P2WPKH with the user's signature alone.** Elapsed this run ${Math.round((Date.now() - t0) / 60_000)} min (the L1 waits dominate).`);

  // ---- 8. cooperative refund on vault B -------------------------------------
  try {
    if (!state.depositB) {
      const dep = await depositToVault({ vault: vaultB, userWallet: wallet, rpc, amountSats: DEPOSIT, feeRateSatVb: 2 });
      const tx = bitcoin.Transaction.fromHex(dep.rawTxHex);
      state.depositB = { txid: dep.txid, vout: tx.outs.findIndex((o) => Buffer.from(o.script).equals(vaultB.p2tr.output)), broadcastAt: new Date().toISOString() }; save();
      rec("8. depositToVault B (from confirmed change)", state.depositB);
    }
    const cB = await waitConfirmations(state.depositB.txid, 1, "deposit B");
    rec("8. deposit B confirmed", cB);
    if (!state.registerB) {
      const fee = state.feeVtxos["1"];
      const reg = await registerVault({ vault: vaultB, outpoint: { fundingTxid: Buffer.from(state.depositB.txid, "hex").reverse(), fundingVout: state.depositB.vout }, userSigner: signerAt(1), inputs: [{ vtxoId: Buffer.from(fee.id, "hex"), valueSats: BigInt(fee.sats) }], outputs: [{ owner: xOnlyAt(1), amount: BigInt(fee.sats) - 1n }], feeSats: 1n, broadcast: { url: `${RPC}/tachi_txBroadcastSync` }, account: { baseUrl: RPC }, confirm: { baseUrl: RPC } });
      state.registerB = { vaultId: reg.vaultIdHex, commit: reg.commit ? { committed: reg.commit.committed, code: reg.commit.code, log: reg.commit.log } : null }; save();
      rec("8. registerVault B", state.registerB);
    }
    const toLocal = buildToLocalP2trOutput({ nodePubkeys: quorum.nodePubkeys, threshold: quorum.threshold, userDelayedPubkey: vaultB.userKey.compressedHex!, toSelfDelay: vaultB.p2tr.exitLeaf.csvBlocks, network: "regtest" });
    const userValue = DEPOSIT - EXIT_FEE;
    const refund = buildRefundPsbt({ vault: vaultB, funding: { txid: state.depositB.txid, vout: state.depositB.vout, valueSats: DEPOSIT, scriptPubKey: vaultB.p2tr.output.toString("hex") }, toLocal, userValueSats: userValue, feeSats: EXIT_FEE });
    const vopts = { maxFeeSats: 1_000n, toLocal, expectedUserValueSats: userValue, expectedDelayedPubkey: vaultB.userKey.xOnly };
    verifyRefundPsbt(refund.psbt, vaultB, vopts);
    await signRefundPsbtAsUser(refund.psbt, signerAt(1), vaultB, vopts as any);
    rec("8. buildRefundPsbt → verify → user-signed (cooperative leaf, needs quorum co-sign)", { toLocalAddress: toLocal.address, toSelfDelay: toLocal.toSelfDelay, threshold: toLocal.threshold, psbtBase64: refund.psbt.toBase64().slice(0, 120) + "…" });
    let cos: unknown;
    try {
      cos = await cosignRefund(refund.psbt, vaultB, { url: `${RPC}/tachi_signTransaction` });
      rec("8. cosignRefund (POST /tachi_signTransaction) — the quorum's half", cos);
      const applied = applyRefundCosignPartials(refund.psbt, (cos as any).response ?? cos, vaultB);
      const refundHex = finalizeRefundPsbt(refund.psbt, vaultB, vopts);
      const refundTx = bitcoin.Transaction.fromHex(refundHex);
      const rid = await btc("sendrawtransaction", [refundHex]);
      state.refund = { txid: rid, applied, at: new Date().toISOString() }; save();
      rec("8. cooperative refund BROADCAST on L1", { txid: rid, applied, vsize: refundTx.virtualSize() });
      const cR = await waitConfirmations(rid, 1, "refund tx");
      rec("8. cooperative refund confirmed (balance now sits in the to_local commitment output; claiming it is another CSV-gated user-only spend)", { ...cR, toLocalAddress: toLocal.address });
    } catch (e) {
      rec("8. cooperative refund — stopped", { error: e instanceof Error ? e.message : String(e), cosignResponse: cos ?? null }, "Verbatim error from the co-sign / finalize / broadcast step.");
    }
  } catch (e) {
    rec("8. cooperative variant — not completed", { error: e instanceof Error ? e.message : String(e) });
  }
  log("Done", `Total elapsed: ${Math.round((Date.now() - t0) / 60_000)} min.`);
}

main().catch((e) => { log("HARD BLOCKER", `\`\`\`\n${e instanceof Error ? (e.stack ?? e.message) : String(e)}\n\`\`\``); process.exit(1); });
