/**
 * End-to-end against the live Tachi regtest daemon — Step 3 of the real-adapter gate.
 * Excluded from `npm test` (needs network + the keys funded by `npm run smoke:tachi`).
 *
 * Boots the real gateway in-process with ADAPTER_MODE=tachi, creates an invoice,
 * pays it from the "customer" key (smoke key index 1), watches the poller take
 * it seen → committed → confirmed, refunds it back out with a real broadcast,
 * and verifies every balance moved. Writes docs/tachi-e2e-output.md.
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { TachiClient } from "@tachibtc/tachi-sdk-ts";
import { getAccountNonce } from "@tachibtc/taurus-vault-core";
import { buildSignedTransferHex, MerchantKeyring, TachiRealAdapter } from "@opentill/adapter";
import { createApp } from "@opentill/gateway";
import type { GatewayConfig } from "@opentill/gateway";

const RPC = process.env.TACHI_RPC_URL ?? "https://rpc-regtest.tachibtc.com";
const STATE = ".tachi-smoke-state.json";
const OUT = "docs/tachi-e2e-output.md";
const AMOUNT = 5_000n;

const lines: string[] = [];
const say = (s: string) => { console.log(s); lines.push(s); };
const j = (x: unknown) => JSON.stringify(x, (_k, v) => (typeof v === "bigint" ? `${v}n` : v), 2);
const block = (title: string, x: unknown) => { say(`\n### ${title}\n\n\`\`\`json\n${j(x)}\n\`\`\``); };
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const smoke = JSON.parse(readFileSync(STATE, "utf8")) as { mnemonic: string; keys: Array<{ address: string; xOnly: string }> };
  const client = new TachiClient({ baseUrl: RPC });
  const keyring = await MerchantKeyring.fromMnemonic(smoke.mnemonic, "regtest");
  const customer = keyring.derive(1, false); // smoke key1: the payer
  const dir = mkdtempSync(join(tmpdir(), "opentill-tachi-e2e-"));

  say(`# Tachi regtest e2e — real settlement round trip\n\nGenerated by \`npm run e2e:tachi\` at ${new Date().toISOString()} against \`${RPC}\`.`);

  const config: GatewayConfig = {
    apiKey: "e2e_key", webhookSecret: "e2e_secret", dbPath: join(dir, "e2e.db"), adapterMode: "tachi",
    port: 0, host: "127.0.0.1", pollIntervalMs: 2_000, expirySweepIntervalMs: 10_000, webhookSweepIntervalMs: 5_000,
    devRoutesEnabled: false, devPublicSimulate: false, sseHeartbeatMs: 15_000, payoutWebhookUrl: null, payoutPollIntervalMs: 2_000,
    webDistPath: join(dir, "no-dist"), merchantName: "Satoshi Beans (regtest)",
    tachi: { rpcUrl: RPC, network: "regtest", mnemonic: smoke.mnemonic, statePath: join(dir, "tachi-adapter.json") },
  };
  const app = await createApp(config, { logger: false });
  const adapter = app.adapter as TachiRealAdapter;
  const till = adapter.keys()[0]!;
  const auth = { authorization: "Bearer e2e_key", "content-type": "application/json" };

  const bal = async (label: string) => ({ label, merchant: await adapter.getBalance(), till: (await client.getBalance(till.address)).balance_sat, customer: (await client.getBalance(customer.address)).balance_sat });
  block("1. balances before", await bal("before"));

  // 2. invoice
  const inv = (await app.app.inject({ method: "POST", url: "/api/invoices", headers: auth, payload: { amountSats: AMOUNT.toString(), memo: "e2e flat white", expiresInSeconds: 900 } })).json() as { id: string; address: string; status: string };
  block("2. POST /api/invoices → invoice (real per-invoice taproot address)", inv);
  const invoiceKey = adapter.keys().find((k) => k.address === inv.address)!;

  // 3. customer pays: plain ledger transfer from key1 to the invoice address
  const payerVtxos = (await client.getAddressVtxos(customer.address, false)).vtxos.filter((v) => !v.spent && !v.locked);
  const fee = 1n;
  const inSum = payerVtxos.reduce((a, v) => a + BigInt(v.amount), 0n);
  if (inSum < AMOUNT + fee) throw new Error(`customer key ${customer.address} has ${inSum} sats; needs ${AMOUNT + fee}. Run npm run smoke:tachi first.`);
  const nonce = await getAccountNonce(Buffer.from(customer.xOnlyHex, "hex"), { baseUrl: RPC });
  const hex = await buildSignedTransferHex({
    signer: keyring.signer(customer), spenderXOnly: Buffer.from(customer.xOnlyHex, "hex"),
    inputs: payerVtxos.map((v) => ({ vtxoId: v.id, valueSats: BigInt(v.amount) })),
    outputs: [{ owner: Buffer.from(invoiceKey.xOnlyHex, "hex"), amountSats: AMOUNT }, { owner: Buffer.from(customer.xOnlyHex, "hex"), amountSats: inSum - AMOUNT - fee }],
    feeSats: fee, nonce,
  });
  const bc = await client.broadcastTxSync(hex);
  block("3. customer broadcastTxSync(payment) — raw verdict", bc);
  if ((bc as any).result?.code !== 0) throw new Error(`payment rejected: ${j(bc)}`);
  const payHash = String((bc as any).result.hash).toLowerCase();
  say(`\nPayment tx hash: \`${payHash}\``);

  // 4. poller drives the invoice: seen → committed → confirmed
  const seen: string[] = [];
  const t0 = Date.now();
  let status = "pending";
  while (Date.now() - t0 < 90_000) {
    const tick = await app.poller.tick();
    const cur = (await app.app.inject({ method: "GET", url: `/api/invoices/${inv.id}`, headers: auth })).json() as { status: string; amountPaidSats: string; payments: Array<{ paymentId: string; status: string }> };
    const line = `t+${((Date.now() - t0) / 1000).toFixed(1)}s tick applied=${tick.applied} cursor=${tick.cursor} invoice=${cur.status} paid=${cur.amountPaidSats} payments=${cur.payments.map((p) => `${p.paymentId.slice(0, 8)}…:${p.status}`).join(",")}`;
    if (seen[seen.length - 1] !== line) { seen.push(line); say(line); }
    status = cur.status;
    if (status === "confirmed") break;
    await sleep(2_000);
  }
  if (status !== "confirmed") throw new Error(`invoice never confirmed (last status ${status})`);
  const detail = (await app.app.inject({ method: "GET", url: `/api/invoices/${inv.id}`, headers: auth })).json();
  block("4. invoice after confirmation (GET /api/invoices/:id)", detail);
  block("4. public checkout payload (GET /pay/api/:id)", (await app.app.inject({ method: "GET", url: `/pay/api/${inv.id}` })).json());
  block("4. balances after payment", await bal("after payment"));

  // 5. refund via the merchant API → real broadcast from a key that can cover amount + fee (the till)
  const refund = await app.app.inject({ method: "POST", url: `/api/invoices/${inv.id}/refund`, headers: auth, payload: { toAddress: customer.address } });
  block(`5. POST /api/invoices/:id/refund → HTTP ${refund.statusCode}`, refund.json());
  if (refund.statusCode !== 200) throw new Error("refund failed");
  const refundTx = (refund.json() as { txId: string }).txId;
  block("5. refund tx on the daemon (getTransaction)", await client.getTransaction(refundTx));

  // 6. balances after
  block("6. balances after refund", await bal("after refund"));
  block("6. per-key ledger view", {
    invoiceKey: await client.getAddressVtxos(inv.address, true),
    till: await client.getAddressVtxos(till.address, true),
    customer: await client.getAddressVtxos(customer.address, true),
  });

  say(`\n## Result\n\n- payment tx: \`${payHash}\`\n- refund tx: \`${refundTx}\`\n- invoice: \`${inv.id}\` → confirmed → refunded\n`);
  await app.close();
  rmSync(dir, { recursive: true, force: true });
  writeFileSync(OUT, lines.join("\n") + "\n");
  console.log(`\nwrote ${OUT}`);
}

main().catch((e) => { console.error("E2E FAILED:", e); writeFileSync(OUT, lines.join("\n") + `\n\n**FAILED:** ${e instanceof Error ? e.message : String(e)}\n`); process.exit(1); });
