/**
 * SPIKE 2 — TxLockForVault: a merchant-style ledger receipt VTXO → locked into
 * a Taurus vault → exited to L1 (unilateral) / co-signed refund (cooperative).
 * Not wired into the product. Every stage prints verbatim daemon/L1 responses
 * and appends to docs/tachi-lock-spike.md; state in .tachi-lock-state.json
 * (gitignored) makes reruns resume. Stops at the first hard blocker.
 *
 *   npm run spike:lock       SPIKE_CSV=1 (test-only; 1008 is the sane default)
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import * as bitcoin from "bitcoinjs-lib";
import * as ecc from "@bitcoinerlab/secp256k1";
import { TachiClient } from "@tachibtc/tachi-sdk-ts";
import { BitcoinCoreRpcClient, WalletAggregator } from "@tachibtc/taurus-wallet-aggregator";
import {
  buildRefundPsbt, buildTachiTxDeposit, buildToLocalP2trOutput, buildUnilateralExitPsbt, cosignRefund, createVault,
  depositToVault, encodeTachiTx, fetchConsensusQuorum, finalizeRefundPsbt, finalizeUnilateralExitPsbt, getAccountNonce,
  getLockedVtxos, listVaults, registerVault, signRefundPsbtAsUser, signTachiTx, signUnilateralExitPsbtAsUser,
  verifyRefundPsbt, verifyUnilateralExitPsbt, vtxoIdFromDeposit, waitForTachiTxCommit, TACHI_TX_VERSION, type TachiTx, type Vault,
} from "@tachibtc/taurus-vault-core";
import { buildSignedTransferHex, MerchantKeyring, vtxoIdFor } from "@opentill/adapter";

bitcoin.initEccLib(ecc);
const RPC = process.env.TACHI_RPC_URL ?? "https://rpc-regtest.tachibtc.com";
const STATE = process.env.SPIKE_STATE ?? ".tachi-lock-state.json";
const DOC = "docs/tachi-lock-spike.md";
const CSV = Number(process.env.SPIKE_CSV ?? "1");
const RECEIPT = 50_000n;   // the "sale"
const DEPOSIT = 50_000n;   // vault L1 funding (matched to the receipt on purpose)
const EXIT_FEE = 500n;
const TX_TYPE_LOCK_FOR_VAULT = 6; // 0x06 per Tachi (VAULT_OPEN=16, VAULT_CLOSE=18 match their 0x10/0x12)
const net = bitcoin.networks.regtest;

type State = Record<string, any>;
const state: State = existsSync(STATE) ? JSON.parse(readFileSync(STATE, "utf8")) : { sections: [] };
if (!state.sections) state.sections = [];
const save = () => { writeFileSync(STATE, JSON.stringify(state, (_k, v) => (typeof v === "bigint" ? v.toString() : v), 2), { mode: 0o600 }); writeFileSync(DOC, `# Tachi lock spike — merchant receipt VTXO → TxLockForVault → vault → L1 (tachi-regtest-1)\n\nGenerated by \`npm run spike:lock\` (scripts/tachi-lock-spike.ts). Every block is a verbatim daemon/L1 response. Exit-leaf CSV for this run: **${CSV} block(s)** (test-only; 1008 is the sane default).\n\n${(state.sections as string[]).join("\n\n")}\n`); };
const j = (x: unknown) => JSON.stringify(x, (_k, v) => typeof v === "bigint" ? `${v}n` : Buffer.isBuffer(v) ? v.toString("hex") : v instanceof Uint8Array ? Buffer.from(v).toString("hex") : v, 2);
const stamp = () => new Date().toISOString().slice(11, 19) + "Z";
function log(title: string, body: string) { const s = `## ${title}\n\n_${stamp()}_\n\n${body}`; console.log("\n" + s); state.sections.push(s); save(); }
const rec = (t: string, v: unknown, note?: string) => log(t, `${note ? note + "\n\n" : ""}\`\`\`json\n${j(v)}\n\`\`\``);
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const client = new TachiClient({ baseUrl: RPC, timeoutMs: 90_000 });
const rpc = new BitcoinCoreRpcClient({ url: RPC, timeoutMs: 90_000 } as any);
const btc = async (method: string, params: unknown[] = []) => { const r = await client.bitcoinRPC({ method, params }); if (r.error) throw new Error(`bitcoinRPC ${method}: ${JSON.stringify(r.error)}`); return r.result as any; };
async function waitConfirmations(txid: string, need: number, label: string, maxMin = 25) {
  const t0 = Date.now();
  for (;;) {
    let c = 0, r: any = null;
    try { r = await btc("getrawtransaction", [txid, true]); c = r?.confirmations ?? 0; } catch (e) { console.log(`  (transient: ${(e as Error).message.slice(0, 80)})`); }
    if (c >= need) return { confirmations: c, blockhash: r.blockhash, waitedSec: Math.round((Date.now() - t0) / 1000) };
    if (Date.now() - t0 > maxMin * 60_000) throw new Error(`timed out after ${maxMin} min waiting for ${label} ${txid}`);
    await sleep(20_000);
  }
}
const verdict = (bc: any) => ({ code: bc?.result?.code, log: bc?.result?.log, hash: String(bc?.result?.hash ?? "").toLowerCase() });

async function main() {
  const t0 = Date.now();
  const kr = await MerchantKeyring.fromMnemonic(state.mnemonic, "regtest");
  const merchant = kr.derive(0, false);   // vault A user key == receipt owner
  const merchant2 = kr.derive(1, false);  // vault B user key
  const customer = kr.derive(5, false);   // stands in for the paying customer
  const agg = WalletAggregator.fromMnemonic(state.mnemonic, { network: "regtest", rpc });
  const wallet = agg.addAccount({ addressType: "p2wpkh" });
  log("Run", `- when: ${new Date().toISOString()}\n- rpc: \`${RPC}\`\n- csvBlocks: ${CSV} (test-only)\n- merchant key (vault A user key, receipt owner): \`${merchant.address}\` (${merchant.path})\n- merchant key 2 (vault B): \`${merchant2.address}\`\n- customer key: \`${customer.address}\` (${customer.path})\n- L1 P2WPKH: \`${state.p2wpkh}\`; faucet txids ${state.faucetTxids.join(", ")} (claimed ${state.faucetClaimedAt})`);

  // ---- 1. a merchant-like receipt VTXO -----------------------------------------
  const mintTo = async (key: ReturnType<typeof kr.derive>, sats: bigint) => {
    const xOnly = Buffer.from(key.xOnlyHex, "hex");
    const nonce = await getAccountNonce(xOnly, { baseUrl: RPC });
    const signed = await signTachiTx(buildTachiTxDeposit({ userXOnly: xOnly, amountSats: sats, nonce, feeSats: 1n }), kr.signer(key));
    const bc = verdict(await client.broadcastTxSync(encodeTachiTx(signed).toString("hex")));
    if (bc.code !== 0) throw new Error(`mint to ${key.address} rejected: ${j(bc)}`);
    await waitForTachiTxCommit(bc.hash, { baseUrl: RPC });
    return { hash: bc.hash, vtxoId: vtxoIdFromDeposit(signed, 0).toString("hex") };
  };
  const payTo = async (from: ReturnType<typeof kr.derive>, toXOnly: Buffer, sats: bigint) => {
    const vtxos = (await client.getAddressVtxos(from.address, false)).vtxos.filter((v) => !v.spent && !v.locked);
    const inSum = vtxos.reduce((a, v) => a + BigInt(v.amount), 0n);
    const nonce = await getAccountNonce(Buffer.from(from.xOnlyHex, "hex"), { baseUrl: RPC });
    const hex = await buildSignedTransferHex({ signer: kr.signer(from), spenderXOnly: Buffer.from(from.xOnlyHex, "hex"), inputs: vtxos.map((v) => ({ vtxoId: v.id, valueSats: BigInt(v.amount) })), outputs: [{ owner: toXOnly, amountSats: sats }, ...(inSum - sats - 1n > 0n ? [{ owner: Buffer.from(from.xOnlyHex, "hex"), amountSats: inSum - sats - 1n }] : [])], feeSats: 1n, nonce });
    const bc = verdict(await client.broadcastTxSync(hex));
    if (bc.code !== 0) throw new Error(`transfer rejected: ${j(bc)}`);
    await waitForTachiTxCommit(bc.hash, { baseUrl: RPC });
    return { hash: bc.hash, vtxoId: vtxoIdFor(bc.hash, 0) };
  };
  if (!state.receipt) {
    const mint = await mintTo(customer, 60_000n);
    const pay = await payTo(customer, Buffer.from(merchant.xOnlyHex, "hex"), RECEIPT);
    state.receipt = { customerMint: mint, paymentTx: pay.hash, vtxoId: pay.vtxoId, amount: RECEIPT.toString(), owner: merchant.xOnlyHex, ownerAddress: merchant.address }; save();
  }
  rec("1. merchant receipt VTXO (customer paid a 50 000-sat 'invoice' by ledger transfer)", { ...state.receipt, merchantVtxosNow: await client.getAddressVtxos(merchant.address, true), receiptOnDaemon: await client.getVtxo(state.receipt.vtxoId) },
    "The customer key was funded by a self-signed ledger deposit (sanctioned on regtest/signet), then paid the merchant key exactly as an invoice payment does. `vtxoId` is the receipt.");

  // ---- 2. vaults (L1-funded + registered), reusing the proven path -----------------
  for (const t of state.faucetTxids) await waitConfirmations(t, 1, "faucet");
  await wallet.sync();
  const quorum = await fetchConsensusQuorum({ baseUrl: RPC });
  const vaultA: Vault = await createVault({ network: "regtest", userWallet: wallet, userKeyIndex: 0, nodePubkeys: quorum.nodePubkeys, threshold: quorum.threshold, csvBlocks: CSV });
  const vaultB: Vault = await createVault({ network: "regtest", userWallet: wallet, userKeyIndex: 1, nodePubkeys: quorum.nodePubkeys, threshold: quorum.threshold, csvBlocks: CSV });
  if (vaultA.userKey.compressedHex?.slice(2) !== merchant.xOnlyHex) throw new Error("vault A user key != merchant receipt key");
  rec("2. createVault A (user key = receipt owner) and B", { A: { address: vaultA.p2tr.address, userKey: vaultA.userKey.compressedHex, csv: vaultA.p2tr.exitLeaf.csvBlocks, threshold: vaultA.p2tr.cooperativeLeaf.threshold }, B: { address: vaultB.p2tr.address, userKey: vaultB.userKey.compressedHex }, wallet: { balance: wallet.balance, utxos: wallet.utxos.length } });
  // Deposits are sequenced: the aggregator only sees CONFIRMED UTXOs, so a second
  // deposit before the first confirms re-selects the same input (bitcoind then
  // rejects it as an insufficient-fee RBF replacement — observed). B waits for A
  // to confirm, and only stage 6 waits for B.
  const deposit = async (name: "A" | "B", vault: Vault) => {
    const key = `deposit${name}`;
    if (state[key]) return;
    await wallet.sync();
    const dep = await depositToVault({ vault, userWallet: wallet, rpc, amountSats: DEPOSIT, feeRateSatVb: 2 });
    const tx = bitcoin.Transaction.fromHex(dep.rawTxHex);
    state[key] = { txid: dep.txid, vout: tx.outs.findIndex((o) => Buffer.from(o.script).equals(vault.p2tr.output)), broadcastAt: new Date().toISOString(), feeSats: dep.feeSats.toString() }; save();
    rec(`2. depositToVault ${name} — L1 funding broadcast`, state[key]);
  };
  await deposit("A", vaultA);
  { const c = await waitConfirmations(state.depositA.txid, 1, "deposit A"); rec("2. deposit A confirmed", c); }
  await deposit("B", vaultB); // broadcast now; its confirmation is awaited in stage 6
  const register = async (name: "A" | "B", vault: Vault, idx: 0 | 1) => {
    const key = `register${name}`;
    if (!state[key]) {
      const fee = state.feeVtxos[String(idx)];
      const reg = await registerVault({ vault, outpoint: { fundingTxid: Buffer.from(state[`deposit${name}`].txid, "hex").reverse(), fundingVout: state[`deposit${name}`].vout }, userSigner: kr.signer(kr.derive(idx, false)), inputs: [{ vtxoId: Buffer.from(fee.id, "hex"), valueSats: BigInt(fee.sats) }], outputs: [{ owner: Buffer.from(kr.derive(idx, false).xOnlyHex, "hex"), amount: BigInt(fee.sats) - 1n }], feeSats: 1n, broadcast: { url: `${RPC}/tachi_txBroadcastSync` }, account: { baseUrl: RPC }, confirm: { baseUrl: RPC } });
      state[key] = { vaultId: reg.vaultIdHex, hash: reg.broadcast.tendermintTxHash, commit: reg.commit ? { committed: reg.commit.committed, code: reg.commit.code, log: reg.commit.log } : null }; save();
      rec(`2. registerVault ${name} (TxVaultOpen)`, state[key]);
    }
  };
  await register("A", vaultA, 0);
  rec("2. daemon view before the lock", { listVaults: await listVaults(vaultA.userKey.compressedHex!, { baseUrl: RPC }), lockedA: await getLockedVtxos(vaultA.p2tr.address, { baseUrl: RPC }), merchantVtxos: await client.getAddressVtxos(merchant.address, true) });

  // ---- 3. TxLockForVault --------------------------------------------------------------
  const lockPsbtBytes = (withInput: boolean, vault: Vault, amount: bigint) => {
    const psbt = new bitcoin.Psbt({ network: net });
    if (withInput) {
      const dep = vault === vaultA ? state.depositA : state.depositB;
      psbt.addInput({ hash: dep.txid, index: dep.vout, sequence: 0xffffffff, witnessUtxo: { script: vault.p2tr.output, value: DEPOSIT } as any });
    }
    psbt.addOutput({ address: vault.p2tr.address, value: amount } as any);
    return Buffer.from(psbt.toBase64(), "base64"); // raw PSBT bytes, exactly as the SDK sets psbtPayload
  };
  async function tryLock(vault: Vault, owner: ReturnType<typeof kr.derive>, receipt: { vtxoId: string; amount: string }, variant: { label: string; outputs: TachiTx["outputs"]; fee: bigint; withInput: boolean }) {
    const xOnly = Buffer.from(owner.xOnlyHex, "hex");
    const nonce = await getAccountNonce(xOnly, { baseUrl: RPC });
    const tx: TachiTx = { version: TACHI_TX_VERSION, type: TX_TYPE_LOCK_FOR_VAULT as any, inputs: [{ vtxoId: Buffer.from(receipt.vtxoId, "hex"), txid: Buffer.alloc(32, 0), vout: 0, valueSats: BigInt(receipt.amount), sigScript: Buffer.alloc(0) }], outputs: variant.outputs, fee: variant.fee, nonce, pubKey: xOnly, signature: Buffer.alloc(0), psbtPayload: lockPsbtBytes(variant.withInput, vault, BigInt(receipt.amount)), vaultPayload: Buffer.alloc(0) };
    const signed = await signTachiTx(tx, kr.signer(owner));
    const hex = encodeTachiTx(signed).toString("hex");
    const out: any = { variant: variant.label, outputs: variant.outputs.map((o) => ({ owner: o.owner, amount: o.amount })), fee: variant.fee, psbtBytes: tx.psbtPayload.length, psbtWithInput: variant.withInput, hexBytes: hex.length / 2 };
    try { out.decode = await client.decodeTransaction(hex); } catch (e) { out.decode = { error: (e as Error).message }; }
    try { out.validate = await client.validateTransaction(hex); } catch (e) { out.validate = { error: (e as Error).message }; }
    const bc = verdict(await client.broadcastTxSync(hex));
    out.broadcast = bc;
    if (bc.code === 0) { const st = await waitForTachiTxCommit(bc.hash, { baseUrl: RPC }); out.commit = { committed: st.committed, code: st.code, log: st.log, state: st.state, type: st.type }; }
    return out;
  }
  const merchantX = Buffer.from(merchant.xOnlyHex, "hex");
  const variants = (vault: Vault, owner: Buffer, amount: bigint) => [
    { label: "V1 outputs=[] fee=1, PSBT: 1 P2TR output only", outputs: [], fee: 1n, withInput: false },
    { label: "V2 outputs=[owner change amount-1] fee=1 (transfer shape)", outputs: [{ owner, amount: amount - 1n, script: Buffer.alloc(0) }], fee: 1n, withInput: false },
    { label: "V3 outputs=[vault taproot key amount-1] fee=1", outputs: [{ owner: Buffer.from(vault.p2tr.taprootOutputKey), amount: amount - 1n, script: Buffer.alloc(0) }], fee: 1n, withInput: false },
    { label: "V4 outputs=[owner 0] fee=1 (zero-value placeholder)", outputs: [{ owner, amount: 0n, script: Buffer.alloc(0) }], fee: 1n, withInput: false },
    { label: "V5 outputs=[] fee=1, PSBT with funding input + 1 P2TR output", outputs: [], fee: 1n, withInput: true },
    { label: "V6 outputs=[owner change amount-1] fee=1, PSBT with funding input", outputs: [{ owner, amount: amount - 1n, script: Buffer.alloc(0) }], fee: 1n, withInput: true },
  ];
  // Finalized exit-leaf PSBT: 1 real input (vault funding outpoint) with a
  // finalScriptWitness, exactly 1 P2TR output paying the vault's own address.
  // This mirrors how the SDK's transfer path fills psbtPayload (a finalized PSBT
  // spending the vault's L1 UTXO). Signed by the user alone via the exit leaf.
  const finalizedSelfSpendPsbt = async (vault: Vault, dep: { txid: string; vout: number }, signer: ReturnType<typeof kr.signer>, outValue: bigint) => {
    const built = buildUnilateralExitPsbt({ vault, funding: { txid: dep.txid, vout: dep.vout, valueSats: DEPOSIT, scriptPubKey: vault.p2tr.output.toString("hex") }, outputs: [{ address: vault.p2tr.address, valueSats: outValue }], feeSats: DEPOSIT - outValue });
    const opts = { maxFeeSats: 100_000n, minCsvBlocks: CSV };
    await signUnilateralExitPsbtAsUser(built.psbt, signer, vault, opts);
    finalizeUnilateralExitPsbt(built.psbt, vault, { ...opts, expectedUserKey: vault.p2tr.exitLeaf.userKey }); // mutates psbt: finalScriptWitness set
    const finalized = built.psbt.data.inputs[0]!.finalScriptWitness !== undefined;
    return { bytes: Buffer.from(built.psbt.toBase64(), "base64"), finalized, outputs: built.psbt.txOutputs.length };
  };
  const wVariants = async (vault: Vault, dep: { txid: string; vout: number }, signer: ReturnType<typeof kr.signer>, owner: Buffer, amount: bigint) => {
    const p1 = await finalizedSelfSpendPsbt(vault, dep, signer, DEPOSIT - EXIT_FEE);
    const depTxidInternal = Buffer.from(dep.txid, "hex").reverse();
    return [
      { label: "W1 finalized exit-leaf PSBT (1 input+finalScriptWitness, 1 P2TR out=vault), outputs=[] fee=1", outputs: [], fee: 1n, psbt: p1.bytes, meta: p1 },
      { label: "W2 same PSBT, outputs=[owner amount-1] fee=1", outputs: [{ owner, amount: amount - 1n, script: Buffer.alloc(0) }], fee: 1n, psbt: p1.bytes, meta: p1 },
      { label: "W3 same PSBT, input.txid=vault funding txid (internal order)+vout, outputs=[] fee=1", outputs: [], fee: 1n, psbt: p1.bytes, meta: p1, inTxid: depTxidInternal, inVout: dep.vout },
      { label: "W4 same PSBT, input.txid=funding (display order), outputs=[owner amount-1] fee=1", outputs: [{ owner, amount: amount - 1n, script: Buffer.alloc(0) }], fee: 1n, psbt: p1.bytes, meta: p1, inTxid: Buffer.from(dep.txid, "hex"), inVout: dep.vout },
    ];
  };
  async function tryLockW(vault: Vault, owner: ReturnType<typeof kr.derive>, receipt: { vtxoId: string; amount: string }, v: any) {
    const xOnly = Buffer.from(owner.xOnlyHex, "hex");
    const nonce = await getAccountNonce(xOnly, { baseUrl: RPC });
    const tx: TachiTx = { version: TACHI_TX_VERSION, type: TX_TYPE_LOCK_FOR_VAULT as any, inputs: [{ vtxoId: Buffer.from(receipt.vtxoId, "hex"), txid: v.inTxid ?? Buffer.alloc(32, 0), vout: v.inVout ?? 0, valueSats: BigInt(receipt.amount), sigScript: Buffer.alloc(0) }], outputs: v.outputs, fee: v.fee, nonce, pubKey: xOnly, signature: Buffer.alloc(0), psbtPayload: v.psbt, vaultPayload: Buffer.alloc(0) };
    const signed = await signTachiTx(tx, kr.signer(owner));
    const hex = encodeTachiTx(signed).toString("hex");
    const out: any = { variant: v.label, psbt: { bytes: v.psbt.length, finalized: v.meta.finalized, outputs: v.meta.outputs }, outputs: v.outputs.map((o: any) => ({ owner: o.owner, amount: o.amount })), fee: v.fee, hexBytes: hex.length / 2 };
    try { out.decode = await client.decodeTransaction(hex); } catch (e) { out.decode = { error: (e as Error).message }; }
    const bc = verdict(await client.broadcastTxSync(hex)); out.broadcast = bc;
    if (bc.code === 0) { const st = await waitForTachiTxCommit(bc.hash, { baseUrl: RPC }); out.commit = { committed: st.committed, code: st.code, log: st.log, state: st.state, type: st.type }; }
    return out;
  }
  if (!state.lockA && !state.vSeriesDone) {
    const attempts: any[] = [];
    for (const v of variants(vaultA, merchantX, RECEIPT)) {
      const r = await tryLock(vaultA, merchant, state.receipt, v);
      attempts.push(r);
      rec(`3. TxLockForVault attempt — ${v.label}`, r, r.broadcast.code === 0 ? "**ACCEPTED (code 0).**" : `Rejected: \`${r.broadcast.log}\``);
      if (r.broadcast.code === 0 && r.commit?.committed) { state.lockA = { variant: v.label, hash: r.broadcast.hash, commit: r.commit }; save(); break; }
      // a committed=false after code 0 means mempool accept but dropped at FinalizeBlock — record and continue
    }
    if (!state.lockA) { state.vSeriesDone = true; save(); rec("3. V-series (unfinalized PSBT) — none accepted", { attempts: attempts.map((a) => ({ variant: a.variant, code: a.broadcast.code, log: a.broadcast.log })) }); }
  }
  if (!state.lockA && !state.wSeriesDone) {
    log("3b. /tachi_txValidate is not evidence", "Control probe: the SDK-encoded bytes with `type=1` (a TRANSFER of the shape we commit routinely) fail `/tachi_txValidate` with the identical `input 0 sigscript: need 16705 bytes` message — that endpoint's decoder mis-parses inputs regardless of type (the README's 'false negatives' warning). Only the broadcast verdict counts. `/tachi_txDecode` parses `type 6` as `lock` correctly.");
    const attempts: any[] = [];
    for (const v of await wVariants(vaultA, state.depositA, kr.signer(merchant), merchantX, RECEIPT)) {
      const r = await tryLockW(vaultA, merchant, state.receipt, v);
      attempts.push(r);
      rec(`3b. TxLockForVault attempt — ${v.label}`, r, r.broadcast.code === 0 ? "**ACCEPTED (code 0).**" : `Rejected: \`${r.broadcast.log}\``);
      if (r.broadcast.code === 0 && r.commit?.committed) { state.lockA = { variant: v.label, hash: r.broadcast.hash, commit: r.commit }; save(); break; }
    }
    if (!state.lockA) { state.wSeriesDone = true; save(); rec("3b. W-series (finalized PSBT) — none accepted", { attempts: attempts.map((a) => ({ variant: a.variant, code: a.broadcast.code, log: a.broadcast.log })) }); }
  }
  // X-series: outputs non-empty (required by the generic check); vary what the
  // post-signature lock rule might key on — PSBT output value and ledger output owner.
  if (!state.lockA) {
    const dep = state.depositA;
    const mk = async (outValue: bigint) => { const p = await finalizedSelfSpendPsbt(vaultA, dep, kr.signer(merchant), outValue); return p; };
    const p50000 = await mk(50_000n).catch((e) => ({ error: (e as Error).message })); // L1-invalid (fee 0) but PSBT-valid?
    const p49999 = await mk(49_999n);
    const p49500 = await mk(49_500n);
    const vaultKey = Buffer.from(vaultA.p2tr.taprootOutputKey);
    const xs: any[] = [];
    if (!("error" in p50000)) xs.push({ label: "X1 PSBT out=50 000 (== VTXO amount), outputs=[owner 49 999] fee=1", outputs: [{ owner: merchantX, amount: 49_999n, script: Buffer.alloc(0) }], fee: 1n, psbt: p50000.bytes, meta: p50000 });
    else rec("3c. X1 skipped — could not build a fee-0 exit PSBT", p50000);
    xs.push({ label: "X2 PSBT out=49 999 (== amount − ledger fee), outputs=[owner 49 999] fee=1", outputs: [{ owner: merchantX, amount: 49_999n, script: Buffer.alloc(0) }], fee: 1n, psbt: p49999.bytes, meta: p49999 });
    xs.push({ label: "X3 PSBT out=49 500, outputs=[vault taproot key 49 999] fee=1", outputs: [{ owner: vaultKey, amount: 49_999n, script: Buffer.alloc(0) }], fee: 1n, psbt: p49500.bytes, meta: p49500 });
    if (!("error" in p50000)) xs.push({ label: "X4 PSBT out=50 000, outputs=[vault taproot key 49 999] fee=1", outputs: [{ owner: vaultKey, amount: 49_999n, script: Buffer.alloc(0) }], fee: 1n, psbt: p50000.bytes, meta: p50000 });
    xs.push({ label: "X5 PSBT out=49 500, outputs=[owner 50 000] fee=0 (no ledger fee)", outputs: [{ owner: merchantX, amount: 50_000n, script: Buffer.alloc(0) }], fee: 0n, psbt: p49500.bytes, meta: p49500 });
    const attempts: any[] = [];
    for (const v of xs) {
      const r = await tryLockW(vaultA, merchant, state.receipt, v);
      attempts.push(r);
      rec(`3c. TxLockForVault attempt — ${v.label}`, r, r.broadcast.code === 0 ? "**ACCEPTED (code 0).**" : `Rejected: \`${r.broadcast.log}\``);
      if (r.broadcast.code === 0 && r.commit?.committed) { state.lockA = { variant: v.label, hash: r.broadcast.hash, commit: r.commit }; save(); break; }
    }
    if (!state.lockA) { rec("3c. X-series — none accepted", { attempts: attempts.map((a) => ({ variant: a.variant, code: a.broadcast.code, log: a.broadcast.log })) }); throw new Error("HARD BLOCKER: TxLockForVault — every constructible shape rejected; with non-empty outputs the generic format check passes (bogus-sig probe) but a post-signature lock-specific rule fails with the same `code 12`, and the daemon exposes no reason"); }
  }
  // ---- 4. verify the lock -----------------------------------------------------------
  rec("4. daemon view AFTER the lock", { lockedA: await getLockedVtxos(vaultA.p2tr.address, { baseUrl: RPC }), receipt: await client.getVtxo(state.receipt.vtxoId), merchantVtxos: await client.getAddressVtxos(merchant.address, true), merchantBalance: await client.getBalance(merchant.address), vaultAddrVtxos: await client.getAddressVtxos(vaultA.p2tr.address, true), listVaults: await listVaults(vaultA.userKey.compressedHex!, { baseUrl: RPC }) });

  // ---- 5. unilateral exit of vault A to L1 ---------------------------------------------
  if (!state.exitA) {
    const built = buildUnilateralExitPsbt({ vault: vaultA, funding: { txid: state.depositA.txid, vout: state.depositA.vout, valueSats: DEPOSIT, scriptPubKey: vaultA.p2tr.output.toString("hex") }, outputs: [{ address: state.p2wpkh, valueSats: DEPOSIT - EXIT_FEE }], feeSats: EXIT_FEE });
    const opts = { maxFeeSats: 1_000n, minCsvBlocks: CSV };
    verifyUnilateralExitPsbt(built.psbt, vaultA, { ...opts, expectedUserKey: vaultA.p2tr.exitLeaf.userKey });
    await signUnilateralExitPsbtAsUser(built.psbt, kr.signer(merchant), vaultA, opts);
    const hex = finalizeUnilateralExitPsbt(built.psbt, vaultA, { ...opts, expectedUserKey: vaultA.p2tr.exitLeaf.userKey });
    const txid = await btc("sendrawtransaction", [hex]);
    state.exitA = { txid, sequence: built.sequence, at: new Date().toISOString() }; save();
    rec("5. unilateral exit broadcast on L1 (user-signed only)", state.exitA);
  }
  const cE = await waitConfirmations(state.exitA.txid, 1, "exit A");
  await wallet.sync();
  rec("5. EXIT CONFIRMED ON L1", { ...cE, exitTxid: state.exitA.txid, l1Wallet: wallet.balance, daemonAfterExit: { lockedA: await getLockedVtxos(vaultA.p2tr.address, { baseUrl: RPC }), receipt: await client.getVtxo(state.receipt.vtxoId), listVaults: await listVaults(vaultA.userKey.compressedHex!, { baseUrl: RPC }) } },
    `The vault's L1 funding output (${DEPOSIT} sats, deposited from L1) left through the exit leaf. Whether the *locked receipt* is what reached L1 is a question of what the lock means — see the daemon view above and the assessment.`);

  // ---- 6. cooperative variant on vault B ----------------------------------------------
  try {
    { const c = await waitConfirmations(state.depositB.txid, 1, "deposit B"); rec("6. deposit B confirmed", c); }
    await register("B", vaultB, 1);
    if (!state.receiptB) { const pay = await payTo(customer, Buffer.from(merchant2.xOnlyHex, "hex"), 5_000n); state.receiptB = { paymentTx: pay.hash, vtxoId: pay.vtxoId, amount: "5000", owner: merchant2.xOnlyHex }; save(); rec("6. second receipt (5 000 sats to merchant key 2)", state.receiptB); }
    if (!state.lockB) {
      const accepted = variants(vaultB, Buffer.from(merchant2.xOnlyHex, "hex"), 5_000n).find((v) => v.label.split(" ")[0] === state.lockA.variant.split(" ")[0])!;
      const r = await tryLock(vaultB, merchant2, state.receiptB, accepted);
      rec(`6. TxLockForVault on vault B — ${accepted.label}`, r);
      if (r.broadcast.code !== 0 || !r.commit?.committed) throw new Error(`lock B rejected: ${r.broadcast.log}`);
      state.lockB = { hash: r.broadcast.hash }; save();
    }
    rec("6. vault B after lock", { lockedB: await getLockedVtxos(vaultB.p2tr.address, { baseUrl: RPC }) });
    const toLocal = buildToLocalP2trOutput({ nodePubkeys: quorum.nodePubkeys, threshold: quorum.threshold, userDelayedPubkey: vaultB.userKey.compressedHex!, toSelfDelay: vaultB.p2tr.exitLeaf.csvBlocks, network: "regtest" });
    const userValue = DEPOSIT - EXIT_FEE;
    const refund = buildRefundPsbt({ vault: vaultB, funding: { txid: state.depositB.txid, vout: state.depositB.vout, valueSats: DEPOSIT, scriptPubKey: vaultB.p2tr.output.toString("hex") }, toLocal, userValueSats: userValue, feeSats: EXIT_FEE });
    const vopts = { maxFeeSats: 1_000n, toLocal, expectedUserValueSats: userValue, expectedDelayedPubkey: vaultB.userKey.xOnly };
    verifyRefundPsbt(refund.psbt, vaultB, vopts);
    await signRefundPsbtAsUser(refund.psbt, kr.signer(merchant2), vaultB, vopts as any);
    const cos = await cosignRefund(refund.psbt, vaultB, { url: `${RPC}/tachi_signTransaction` });
    rec("6. cosignRefund (/tachi_signTransaction)", cos);
    const hex = finalizeRefundPsbt(refund.psbt, vaultB, vopts);
    const rid = await btc("sendrawtransaction", [hex]);
    state.refundB = { txid: rid, at: new Date().toISOString() }; save();
    rec("6. cooperative refund broadcast on L1", state.refundB);
    const cR = await waitConfirmations(rid, 1, "refund B");
    rec("6. cooperative refund confirmed", { ...cR, toLocalAddress: toLocal.address, lockedBAfter: await getLockedVtxos(vaultB.p2tr.address, { baseUrl: RPC }) });
  } catch (e) { rec("6. cooperative variant — stopped", { error: e instanceof Error ? e.message : String(e) }); }
  log("Done", `Elapsed this run ${Math.round((Date.now() - t0) / 60_000)} min.`);
}
main().catch((e) => { log("HARD BLOCKER", `\`\`\`\n${e instanceof Error ? (e.stack ?? e.message) : String(e)}\n\`\`\``); process.exit(1); });
